### ISSUE TITLE
about equation7

### ISSUE THREAD

**Issue by BJQ123456** [liming-ai/ControlNet_Plus_Plus#8]
Great work! I would like to ask why the input for the predicted noise in Equation 7 is  𝑡−1 instead of 𝑡 ? Looking forward to your response, thank you.

**Comment by liming-ai** [comment]
> Great work! I would like to ask why the input for the predicted noise in Equation 7 is 𝑡−1 instead of 𝑡 ? Looking forward to your response, thank you.

Thanks for the question. I believe this is a mistake in our paper, and it should be $t$ instead of $t-1$ like you said. The correct formulation should be:
$x_0 \approx x_0^{\prime}=\frac{x_t^{\prime}-\sqrt{1-\alpha_t} \epsilon_\theta\left(x_t^{\prime}, c_v, c_t, t\right)}{\sqrt{\alpha_t}}$

We will correct this mistake in the following version. Sorry for the misunderstanding and thanks again for your question.
